baseURL = "test.catonacomputer.com"
languageCode = "en-us"
title = "Cat on a Computer"
theme = "hugo-theme-dream"

enableRobotsTXT = true

[params]
  author = "Sarah Christoff"
  motto = "Breaking Things and Learning Fast"
  #description = ""
  avatar = "/img/me.png"

  email = "sarah.christoff13@gmail.com"
  github = "s-christoff"
  linkedin = "sarahchristoff25"
  # codepen = ""
  # stackoverflow = ""

  siteStartYear = 2017
  aboutHeader = "AboutMe"

  paginate = 10

  # favicon = "/img/catonacomplogo.png"